// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/categories.proto

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	data/categories.proto
	data/session.proto
	data/user.proto

It has these top-level messages:
	CategoriesRequest
	CategoriesReply
	Session
	User
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CategoriesRequest struct {
	User uint64 `protobuf:"varint,1,opt,name=user" json:"user,omitempty"`
}

func (m *CategoriesRequest) Reset()                    { *m = CategoriesRequest{} }
func (m *CategoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoriesRequest) ProtoMessage()               {}
func (*CategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CategoriesRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

type CategoriesReply struct {
	MostSeen         uint64 `protobuf:"varint,1,opt,name=most_seen,json=mostSeen" json:"most_seen,omitempty"`
	BestFriend       uint64 `protobuf:"varint,2,opt,name=best_friend,json=bestFriend" json:"best_friend,omitempty"`
	Crush            uint64 `protobuf:"varint,3,opt,name=crush" json:"crush,omitempty"`
	MutualLove_7Days uint64 `protobuf:"varint,4,opt,name=mutual_love_7days,json=mutualLove7days" json:"mutual_love_7days,omitempty"`
	MutualLoveGlobal uint64 `protobuf:"varint,5,opt,name=mutual_love_global,json=mutualLoveGlobal" json:"mutual_love_global,omitempty"`
}

func (m *CategoriesReply) Reset()                    { *m = CategoriesReply{} }
func (m *CategoriesReply) String() string            { return proto.CompactTextString(m) }
func (*CategoriesReply) ProtoMessage()               {}
func (*CategoriesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CategoriesReply) GetMostSeen() uint64 {
	if m != nil {
		return m.MostSeen
	}
	return 0
}

func (m *CategoriesReply) GetBestFriend() uint64 {
	if m != nil {
		return m.BestFriend
	}
	return 0
}

func (m *CategoriesReply) GetCrush() uint64 {
	if m != nil {
		return m.Crush
	}
	return 0
}

func (m *CategoriesReply) GetMutualLove_7Days() uint64 {
	if m != nil {
		return m.MutualLove_7Days
	}
	return 0
}

func (m *CategoriesReply) GetMutualLoveGlobal() uint64 {
	if m != nil {
		return m.MutualLoveGlobal
	}
	return 0
}

func init() {
	proto.RegisterType((*CategoriesRequest)(nil), "data.CategoriesRequest")
	proto.RegisterType((*CategoriesReply)(nil), "data.CategoriesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Categories service

type CategoriesClient interface {
	GetCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesReply, error)
}

type categoriesClient struct {
	cc *grpc.ClientConn
}

func NewCategoriesClient(cc *grpc.ClientConn) CategoriesClient {
	return &categoriesClient{cc}
}

func (c *categoriesClient) GetCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesReply, error) {
	out := new(CategoriesReply)
	err := grpc.Invoke(ctx, "/data.Categories/GetCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categories service

type CategoriesServer interface {
	GetCategories(context.Context, *CategoriesRequest) (*CategoriesReply, error)
}

func RegisterCategoriesServer(s *grpc.Server, srv CategoriesServer) {
	s.RegisterService(&_Categories_serviceDesc, srv)
}

func _Categories_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoriesServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Categories/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoriesServer).GetCategories(ctx, req.(*CategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Categories_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.Categories",
	HandlerType: (*CategoriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _Categories_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/categories.proto",
}

func init() { proto.RegisterFile("data/categories.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xa6, 0xa2, 0x23, 0x52, 0x3b, 0x58, 0x5c, 0xf4, 0xa0, 0xe4, 0xa2, 0x88, 0x44,
	0xd0, 0x83, 0x67, 0x11, 0xec, 0x45, 0x10, 0xea, 0x03, 0x84, 0x4d, 0x33, 0xd6, 0xc2, 0x36, 0x1b,
	0x77, 0x66, 0x0b, 0x79, 0x3a, 0x5f, 0x4d, 0x32, 0x15, 0x1b, 0xe8, 0x6d, 0xf7, 0xfb, 0xbe, 0xcb,
	0xfc, 0x30, 0xae, 0xac, 0xd8, 0xfb, 0x99, 0x15, 0x9a, 0xfb, 0xb0, 0x20, 0xce, 0x9b, 0xe0, 0xc5,
	0x63, 0xda, 0xe1, 0xec, 0x1a, 0x46, 0x2f, 0xff, 0x66, 0x4a, 0xdf, 0x91, 0x58, 0x10, 0x21, 0x8d,
	0x4c, 0xc1, 0x24, 0x57, 0xc9, 0x4d, 0x3a, 0xd5, 0x77, 0xf6, 0x93, 0xc0, 0xb0, 0x5f, 0x36, 0xae,
	0xc5, 0x0b, 0x38, 0x5c, 0x7a, 0x96, 0x82, 0x89, 0xea, 0xbf, 0xf8, 0xa0, 0x03, 0x1f, 0x44, 0x35,
	0x5e, 0xc2, 0x51, 0x49, 0x2c, 0xc5, 0x67, 0x58, 0x50, 0x5d, 0x99, 0x5d, 0xd5, 0xd0, 0xa1, 0x57,
	0x25, 0x78, 0x0a, 0x83, 0x59, 0x88, 0xfc, 0x65, 0xf6, 0x54, 0xad, 0x3f, 0x78, 0x0b, 0xa3, 0x65,
	0x94, 0x68, 0x5d, 0xe1, 0xfc, 0x8a, 0x8a, 0xa7, 0xca, 0xb6, 0x6c, 0x52, 0x2d, 0x86, 0x6b, 0xf1,
	0xe6, 0x57, 0xa4, 0x18, 0xef, 0x00, 0xfb, 0xed, 0xdc, 0xf9, 0xd2, 0x3a, 0x33, 0xd0, 0xf8, 0x64,
	0x13, 0x4f, 0x94, 0x3f, 0xbc, 0x03, 0x6c, 0x0e, 0xc0, 0x67, 0x38, 0x9e, 0x90, 0xf4, 0xc0, 0x59,
	0xde, 0x0d, 0x92, 0x6f, 0xad, 0x71, 0x3e, 0xde, 0x16, 0x8d, 0x6b, 0xb3, 0x9d, 0x72, 0x5f, 0x87,
	0x7c, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x65, 0x9e, 0xf0, 0x36, 0x61, 0x01, 0x00, 0x00,
}
